# Generated by Django 3.1.5 on 2021-01-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=1200)),
                ('img', models.CharField(max_length=750)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
