# Generated by Django 3.1.5 on 2021-02-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='img',
            field=models.CharField(default='', max_length=750),
        ),
    ]
