# Generated by Django 3.1.5 on 2021-02-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20210201_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='img',
            field=models.CharField(default='', max_length=750, null=True),
        ),
    ]
