# Generated by Django 3.1.5 on 2021-01-30 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0002_tweet_user_id'),
        ('favourites', '0003_favourite_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='tweet_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_Bookmark', to='tweets.tweet'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user_Id', 'tweet_Id')},
        ),
    ]
