# Generated by Django 3.1.5 on 2021-01-27 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('followers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='following_From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_From', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='following_To',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_To', to=settings.AUTH_USER_MODEL),
        ),
    ]
