# Generated by Django 3.1.5 on 2021-02-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='img',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
