# Generated by Django 3.1.5 on 2021-01-27 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_comment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tweet_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tweets.tweet'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
