# Generated by Django 3.1.5 on 2021-01-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.CharField(default='https://www.w3schools.com/howto/img_avatar.png', max_length=1000),
        ),
    ]
